// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package internal

import (
	"github.com/dushixiang/prism/internal/config"
	"github.com/dushixiang/prism/internal/handler"
	"github.com/dushixiang/prism/internal/ioc"
	"github.com/dushixiang/prism/internal/service"
	"github.com/google/wire"
	"go.uber.org/zap"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func ProviderContainer(logger *zap.Logger, db *gorm.DB, conf *config.Config) *ioc.Container {
	accountService := service.NewAccountService(logger, db)
	userService := service.NewUserService(logger, db, accountService)
	userHandler := handler.NewUserHandler(userService)
	accountHandler := handler.NewAccountHandler(accountService, userService)
	propertyService := service.NewPropertyService(db)
	propertyHandler := handler.NewPropertyHandler(propertyService)
	binanceService := service.NewBinanceService(conf, logger)
	technicalAnalysisService := service.NewTechnicalAnalysisService(logger)
	llmAnalysisService := service.NewLLMAnalysisService(conf, logger)
	newsService := service.NewNewsService(logger, db, llmAnalysisService)
	marketHandler := handler.NewMarketHandler(binanceService, technicalAnalysisService, llmAnalysisService, newsService, logger)
	newsHandler := handler.NewNewsHandler(newsService, logger)
	container := &ioc.Container{
		UserHandler:        userHandler,
		AccountHandler:     accountHandler,
		PropertyHandler:    propertyHandler,
		MarketHandler:      marketHandler,
		NewsHandler:        newsHandler,
		UserService:        userService,
		AccountService:     accountService,
		PropertyService:    propertyService,
		NewsService:        newsService,
		BinanceService:     binanceService,
		TechnicalService:   technicalAnalysisService,
		LLMAnalysisService: llmAnalysisService,
	}
	return container
}

// wire.go:

var appSet = wire.NewSet(
	serviceSet,
	apiSet, wire.Struct(new(ioc.Container), "*"),
)

var apiSet = wire.NewSet(handler.NewUserHandler, handler.NewAccountHandler, handler.NewPropertyHandler, handler.NewMarketHandler, handler.NewNewsHandler)

var serviceSet = wire.NewSet(service.NewUserService, service.NewAccountService, service.NewPropertyService, service.NewNewsService, service.NewBinanceService, service.NewLLMAnalysisService, service.NewTechnicalAnalysisService)
